// Currencies
export const LOAD_CURRENCIES = 'LOAD_CURRENCIES'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'
export const RESET_FILTERS = 'RESET_FILTERS'

// Coin Market Cap
export const RECIEVE_CURRENCIES = 'RECIEVE_CURRENCIES'
export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'
export const UPDATE_CURRENCY_HISTORY = 'UPDATE_CURRENCY_HISTORY'
export const UPDATE_CURRENCIES = 'UPDATE_CURRENCIES'
export const RECIEVE_CURRENCY_HISTORY = 'RECIEVE_CURRENCY_HISTORY'

// Fixer
export const UPDATE_FIAT_EXCHANGE_RATES = 'UPDATE_FIAT_EXCHANGE_RATES'

// ShapeShift
export const RECIEVE_SHAPESHIFT_RATES = 'RECIEVE_SHAPESHIFT_RATES'

