// ALL
export const LOAD_CURRENCIES = 'LOAD_CURRENCIES'
export const UPDATE_FILTERS = 'UPDATE_FILTERS'

// Coin Market Cap
export const RECIEVE_CURRENCIES = 'RECIEVE_CURRENCIES'
export const RECIEVE_CURRENCY_HISTORY = 'RECIEVE_CURRENCY_HISTORY'

// ShapeShift
export const RECIEVE_SHAPESHIFT_RATES = 'RECIEVE_SHAPESHIFT_RATES'

